Practice/wedding
Megumikawa/manabito-practice pull request #6
Opened 2020-03-03 08:19 UTC by Megumikawa

レビューをお願いします。

2020-03-03 14:39 UTC, sararilfy commented
■デザインチェック(全体)
- 間違い探しをしましょう！

■デザインチェック(PC)
index.html
- グローバルナビゲーションのフォントが明朝体になっていない
- グローバルナビゲーションの分割線がよーくみたら黒い線があってしかもグラデーションが入っている
- スライドショーは自動で次のスライドに行くようにしたらいいかも
- 「お知らせ」タイトルと日付の文字サイズ
-  お知らせの点線はdashedではなくdotted、点線の長さが足りない
-  フッターの「東京都千代田...」が画面下にピタッとくっついているので、少し開ける
- フッターの線が白だけではなく、うっすらグレーの線もつける
- 「ページの先頭へ戻る」の文字サイズと下線が無い

concept.html
- グローバルナビゲーションの選ばれた状態は反映しない？
- 「結婚式場のコンセプト」と「全てのお客様のご満足のために」のタイトル文字サイズが大きい
- 「結婚式場のコンセプト」のタイトルの線の色が違う
- 「結婚式場のコンセプト」のタイトルの線は太い線と細い線の組み合わせなのでdoubleでは実現できないので、工夫が必要ですね。
- 「全てのお客様のご満足のために」タイトルとその下の画像との距離をもう少し開ける

contact.html
- テーブルと「確認する」ボタンとの余白をもう少し開ける
- 「確認する」ボタンをもう少し大きくする

■デザインチェック(SP)
※デザイン見本がないので正解がわからなかったのですが、気になったのは以下です
- お問い合わせフォームの「確認する」ボタンが真ん中に来ていない
- フッターの文字がピタッと上下くっついている


■ブラウザチェック
- Safariだとテキストが全部明朝体になってます
- 事務所に来たら、Windowsでもチェックしてみたいと思います
※自分でブラウザチェックしましょう！
→レビューしてくれる人は基本みてくれません！また、お客さん（エンドユーザー）はどのブラウザを使うかわかりません！
▼チェックすべきもの
（Windows: IE11, Edge, firefox, chrome）
（Mac: Safari, firefox, chrome）
※今回は割愛しますが、必ずスマートフォンの実機でも確認しましょう！（iphoneとAndroid両方！）

2020-03-03 15:38 UTC, sararilfy requested changes
コメントしてみました！

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +    <title>HOTEL INPERIAL RESORT TOKYO</title>
INPERIALの綴りが違う！検索置換をするといいですよ

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +    <title>HOTEL INPERIAL RESORT TOKYO</title>
レスポンシブ対応する場合は、viewport設定を入れましょう
`<meta name="viewport" content="width=device-width, initial-scale=1">`

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +    <link rel="stylesheet" href="css/style.css">
responsive.cssが入っていない...？
`<link rel="stylesheet" href="css/responsive.css" media="screen and (max-width: 768px)">`

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
normalize.cssがindex.htmlにしか入っていないようです

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +      <div class="gnav">
`class="gnav"`は`<ul>`タグに移行して、`<div>`タグを削除しても実現できそうです。
なるべく`<div>`タグは少なくする方が良いです（`<div>`が増えると読みにくいソースコードになり、また読み込み速度も遅くなるはずなので）

ただ、今回は、`<nav>`タグに変更しましょう
http://www.htmq.com/html5/nav.shtml

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +      <div class="footer-foot">
`<div class="footer-foot">`このタグの閉じタグがないようです

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +        <copyright>Copyright 2014 HOTEL IMPERIAL RESORT TOKYO <br class="footer-info">All right reserved.</copyright>
`<copyright>`というタグはありません！
`<small>`で対応しましょう
http://www.htmq.com/html5/small.shtml

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +        <div class="sub">
` <div class="sub">`は`<aside>`とも思いましたが、`<nav>`が良さそうです
http://www.htmq.com/html5/aside.shtml

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/bridalfair.html
> +          <h1>ブライダルフェア</h1>
`<h1>`は`<section>`のなかに入れましょう

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/bridalfair.html
> +            <span>各会場の様子やお料理、ドレスをはじめ、弊社プランナーがお二人のウェディングをご提案させていただきます。</span>
ここは`<span>`より`<p>`が良いでしょう

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/concept.html
> +            <img src="images/concept_photo1.jpg" alt="コンセプト写真1" width="250" height="180">
1. この画像は挿絵になるので`<figure>`で囲みましょう
http://www.htmq.com/html5/figure.shtml
2. alt属性は「コンセプト写真1」よりももっとこの写真やこの部分の文脈を表すものが良いです（Googleなどのクローラーがヒントにする＆画像検索で表示されるテキストになる...SEO対策）
3. 画像名はアンダースコアではなく、ハイフンでつなぎましょう。クローラーはハイフンで単語を読み取ります。`concept_photo1.jpg`→`concept-photo1.jpg`
（他の画像もですね！今回の修正は割愛して良いので、次回から気をつけてください！）

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/concept.html
> +          <h1>結婚式場のコンセプト</h1>
`<h1>`と下の`<section>`二つを囲む`<section>`がもう一つ必要です。

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/contact.html
> +                <tr><th>お名前（必須）</th><td><input type="text" name="name" required></td></tr>
フォームはlabelタグを使うと、ユーザビリティ良くなります
http://www.htmq.com/html5/label.shtml

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/base.html
> +        <p id="pagetop" class="pagetop"><a>ページの先頭へ戻る</a></p>
JSでページの戻すなら、`<a>`タグは不要だと思います。

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/css/common.css
> +a:hover {
`<a>`タグの:hoverはresponsive.cssで打ち消しましょう。スマートフォン実機だと１クリックでリンクできません

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/css/common.css
> +	list-style-type: none;
`list-type`で記載しましょう
http://www.htmq.com/style/list-style.shtml

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/css/common.css
> +	background-image: url(../images/breadcrumb_arrow.png);
background系はまとめて記載しましょう
http://www.htmq.com/style/background.shtml

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/css/responsive.css
> +	border: 1px solid #f3f2e9;
borderはまとめて書くべきなのですが、どの辺りでこの記載になったかお聞きしたいです！
http://www.htmq.com/style/border.shtml
また、`#nav_plan`はどこにありますか？

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/index.html
> +      <div>
この`<div>`は何もしていないようなので、削除してください

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/index.html
> +          <h2>お知らせ</h2>
`<main>`の中に一つ`<section>`で囲みましょう

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/index.html
> +          <ul class="noticed">
ulは箇条書きで、並べ替えてもOKなタグなので、olが良いかも。
`<dl><dt><dd>`でマークアップする手もあります。

2020-03-03 15:38 UTC, sararilfy commented on practice_wedding/plan.html
> +                <tr><th >項目</th><th>説明</th></tr>
`<th >`のスペースを削除

2020-03-03 15:51 UTC, sararilfy requested changes
コメント第２弾です。

2020-03-03 15:51 UTC, sararilfy commented on practice_wedding/css/style.css
> +@media screen and (max-width:767px){
responsive.cssの内容をこっちに持ってきたということですかね？
その場合でしたら、不要ファイルということでresponsive.cssを削除しましょう！

2020-03-03 15:51 UTC, sararilfy commented on practice_wedding/css/style.css
> +.noticed li {
もし、テキストが改行するくらい入ってしまったら崩れるので、timeやpタグに幅指定などして対策しましょう

2020-03-03 15:51 UTC, sararilfy commented on practice_wedding/base.html
> +        <p>東京都千代田区X-X-X 電話 0120-000-XXX<br class="footer-info"> 営業時間 11:00〜20:00(水曜日定休)</p>
ここは`<p>`ではなく`<address>`で良いです
http://www.htmq.com/html5/address.shtml

2020-03-03 15:51 UTC, sararilfy commented on practice_wedding/css/style.css
> +  float: right;
回り込みの解除はどこでやっていますかね？

2020-03-03 15:51 UTC, sararilfy commented on practice_wedding/plan.html
> +            <span>標準的なプラン例</span>
タイトルに見えるので spanではなく、h2

2020-03-03 15:51 UTC, sararilfy commented on practice_wedding/bridalfair.html
> +            <span>各会場の様子やお料理、ドレスをはじめ、弊社プランナーがお二人のウェディングをご提案させていただきます。</span>
ここは段落とみなせるのでpタグ

2020-03-05 10:02 UTC, sararilfy commented
デザインの修正点です。もう少し！

## TOPページ
* グロナビの文字サイズがまだ大きい
* お知らせのタイトル、日付がまだ大きい
* フッターがまだピタッと画面にくっついてます
* 東京都千代田〜とコピーライトが今度は開きすぎ

## concept.html
* グロナビの黄色いところの文字色が違う（他のページも）
* 結婚式場のコンセプトのタイトル、線の太さと余白がまだ大きい

2020-03-05 10:19 UTC, sararilfy requested changes
ソースコードの修正点第１弾

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/js/script.js
>    'usestrict';
`use strict`が正しいです！
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Strict_mode

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/js/script.js
> +  auto: true,
インデントを揃えて、一つ下げましょう。

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/contact.html
> -          <div>
閉じタグになっていません。

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/contact.html
> +        <div class="h1-outer">
`<section>`が無い状態なので、コンテンツ全体を`<section>`で囲みましょう。

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/plan.html
>            <h1>プランのご案内</h1>
ここもページに`<section>`が無い状態なので、コンテンツ全体を`<section>`で囲みましょう。

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/plan.html
> +        <div class="plan-table">
ここは`<table>`を`<div>`で囲む必要はなさそうです。
`<table class="plan-table">`で事足りそう。

2020-03-05 10:19 UTC, sararilfy commented on practice_wedding/css/style.css
>    background-repeat: no-repeat;
image とrepeatしか設定しない場合も、backgroundで位置指定まで全部書いたほうがわかりやすいし、不具合が出にくいです。
`background: url(../images/bg_h2_head.png) no-repeat left top ;`

2020-03-06 05:06 UTC, sararilfy requested changes

2020-03-06 05:06 UTC, sararilfy commented on practice_wedding/css/style.css
> +  border-radius: 5px 0 0 5px;
.gnav-concept a, .gnav-plan a, .gnav-bridalfair a, ...と全く同じスタイルの当て方が何度も出ているので、
```
.gnav ul li.current-page {
  background-color: #d7d2b4;
}
```
というclassを作って、このclassを各ページのHTMLに当てていくのがスマートかと。
（この`background-color: #d7d2b4;`の記述が１回で済む）

2020-03-06 05:06 UTC, sararilfy commented on practice_wedding/css/style.css
> +  border-radius: 5px 0 0 5px;
`border-radius: 5px 0 0 5px;`は57行目に以下のように追加することもできます。
282行目の.gnav-contact aも同様
```
.gnav li:first-child,
.gnav li:first-child a {
  border-radius: 5px 0 0 5px;
}
.gnav li:last-child,
.gnav li:last-child a {
  border-radius: 0 5px 5px 0;
}
```

なので、SPの方も、
```
.gnav-concept a {
    border-radius: 0;
  }
.gnav-contact a {
  border-radius: 0;
}
```
などが
```
.gnav li:first-child,
.gnav li:first-child a,
.gnav li:last-child,
.gnav li:last-child a {
  border-radius: 0;
}
```
になると思います。

2020-03-06 05:06 UTC, sararilfy commented on practice_wedding/css/style.css
> +}
clearfixはこれだけでは足りません。`content`と `display: block;`も必要です。
https://qiita.com/mariofujisaki/items/2ad1de8432d7249afadc

また、`.concept-photo1::after`にもfloatがかかっているので、clearfixをかけましょう

```
.concept-photo1::after,
.concept-photo2::after {
  content: "";
  display: block;
  clear: both;
}
```

2020-03-06 05:06 UTC, sararilfy commented on practice_wedding/css/style.css
> +input[type="submit"] {
今回は問題ないのでアドバイスなのですが、
この辺りの、`input[type="submit"]`, `textarea`, `input`, `textarea` は、
`.contact-table input[type="submit"] { ... } `のように制限をかけたほうがいいですね。
今回のような小規模なサイトだったら問題ないのですが、
仮に複数フォームがある場合（例えばヘッダーに検索窓があるとか）は、
そちらも影響を受けてしまいますので。

2020-03-06 05:06 UTC, sararilfy commented on practice_wedding/css/style.css
> +    opacity:.5;
ここまで一緒であれば、
```
  .gnav ul li a:hover,
  .breadcrumb a:hover,
  .sub ul li a:hover,
  .footer-head p:hover {
    opacity:.5;
  }
```
で良いかと。

2020-03-06 05:06 UTC, sararilfy commented on practice_wedding/css/style.css
> +}
インデントはきっちり揃えましょう！
465行目も！

2020-03-06 07:18 UTC, Megumikawa commented
再修正しました。レビューをお願いします。

2020-03-07 09:21 UTC, sararilfy requested changes

2020-03-07 09:21 UTC, sararilfy commented on practice_wedding/plan.html
> +        </section>
再修正ありがとうございます！もう後2点で最後です！

①`<section>`は囲ったところが章になるので、
今のままだと、「標準的なプラン例」が別の章となり、関連づけがなくなっていて、
さらにプラン表が含まれていません。
以下のように修正してもらえると嬉しいです！

```
<main>
  <section>
    <div class="h1-outer">
      <h1>プランのご案内</h1>
    </div>
    <section>
      <div class="plan-caption">
        <h2>標準的なプラン例</h2>
        <p>標準的な内容のプランをご紹介します。実際のプランはお客様に合わせてご提案いたしますので、お気軽にお問い合わせください。</p>
      </div>
      <div class="plan-table">
        <table>
          略...
        </table>
      </div>
    </section>
  </section>
</main>
```

2020-03-07 09:21 UTC, sararilfy commented on practice_wedding/plan.html
> +          <h3>標準的なプラン例</h3>
②hタグは1,2,3...と順番に、大見出し・中見出し・小見出し...のように使うのが基本ルールですので、
`<h1>`の次は`<h2>`でお願いします。
（ここは前回見落としていたかもしれません...すみません。）

2020-03-09 04:32 UTC, Megumikawa commented
sectionとh3の修正をしました。

2020-03-09 04:47 UTC, merged